
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: bob
  password: 1234
  host: localhost
  port: 5432

development:
  <<: *default
  database: new_pro_development

 
test:
  <<: *default
  database: new_pro_test


